### ISSUE TITLE
[ Bug ] changes swww walpaper when apply

### ISSUE THREAD

**Issue by nx-smul** [jhideki/pywal-spicetify#10]
it changess swww walpaper after applying command

**Comment by jhideki** [comment]
ummm how can i re-create this issue?

**Comment by nx-smul** [comment]
try chaiiging walpaper using swww then pywal-spicetify then spicetify apply. it just swich back to some random art cover or last walpaper I had. only way to fix this by clearing cache folder

**Comment by Jeflux** [comment]
I've noticed that wal seems to set the wallpaper if not ran with `-n`. Looks like wal is ran with only the `-w` flag here https://github.com/jhideki/pywal-spicetify/blob/2c97c69e92a34657ddfd7d82904c05f9a6307314/src/wal.rs#L23

**Comment by nx-smul** [comment]
nice. kindly fix it and update! thanks

**Comment by jhideki** [comment]
feel free to create a pr for this and i'll close the issue if its fixed

**Comment by nx-smul** [comment]
> I've noticed that wal seems to set the wallpaper if not ran with `-n`. Looks like wal is ran with only the `-w` flag here
> 
> https://github.com/jhideki/pywal-spicetify/blob/2c97c69e92a34657ddfd7d82904c05f9a6307314/src/wal.rs#L23

this worked I'll create a pr
