### ISSUE TITLE
wal silently errors

### ISSUE THREAD

**Issue by VlaDexa** [jhideki/pywal-spicetify#5]
https://github.com/jhideki/pywal-spicetify/blob/81e1be0ae0a591ba927a55694b0877008d209dcd/src/wal.rs#L23-L26
There is no `wal -w`
```sh
usage: wal [-h] [-a "alpha"] [-b background] [--backend [backend]] [--theme [/path/to/file or theme_name]] [--iterative] [--saturate 0.0-1.0] [--preview] [--vte] [-c] [-i "/path/to/img.jpg"] [-l] [-n] [-o "script_name"] [-q] [-r] [-R] [-s] [-t] [-v] [-e]
wal: error: unrecognized arguments: -w
```

**Comment by jhideki** [comment]
You might have a different version idk 
`➜  ~ wal -h
usage: wal [-h] [-a "alpha"] [-b background] [--fg foreground] [--backend [backend]]
           [--theme [/path/to/file or theme_name]] [--iterative] [--cols16 [method]]
           [--recursive] [--saturate 0.0-1.0] [--preview] [--vte] [-c]
           [-i "/path/to/img.jpg"] [-l] [-n] [-o "script_name"] [-p "theme_name"] [-q]
           [-r] [-R] [-s] [-t] [-v] [-w] [-e]`

**Comment by VlaDexa** [comment]
Could you please give me a link to the version you use? I just downloaded python-pywal from AUR

**Comment by jhideki** [comment]
Oh wait my bad, I forgot I was using a fork of pywal  not the original version. here is the [repo](https://github.com/eylles/pywal16).
I will update the dependencies accordingly. Could be worth looking into adding support for the original wal so I'll create an issue for this.

**Comment by VlaDexa** [comment]
> I will update the dependencies accordingly.

As of 0.1.1-1, AUR package still accepts regular pywal. Can you please change AUR dependencies?
You can just bump pkgrel with newer deps on AUR, it's not necessary to make a new version release.

**Comment by jhideki** [comment]
just updated the pkgbuild on the AUR. it should no longer have pywal as a dep

**Comment by VlaDexa** [comment]
I think you forgot to bump the pkgrel, so it won't autoupdate on aur helpers such as yay. But still, thanks!

**Comment by jhideki** [comment]
Did I miss something? I thouhgt I just needed to updated my PKGBUILD and .SRCINFO. Here is the updated info on the AUR.
```bash
yay -Si pywal-spicetify
Repository                    : aur
Name                          : pywal-spicetify
Version                       : 0.1.1-1
Description                   : Apply wal colors to spicetify
URL                           : https://github.com/jhideki/pywal-spicetify
Licenses                      : MIT
Groups                        : None
Provides                      : None
Depends On                    : pywal-16-colors  spicetify-cli
Optional Deps                 : None
Make Deps                     : cargo  git
Check Deps                    : None
Conflicts With                : None
Replaces                      : None
AUR URL                       : https://aur.archlinux.org/packages/pywal-spicetify
First Submitted               : Sat 13 Jul 2024 08:55:00 AM PDT
Keywords                      : None
Last Modified                 : Mon 29 Jul 2024 09:25:54 PM PDT
Maintainer                    : jhideki
Popularity                    : 0.000000
Votes                         : 0
Out-of-date                   : No```

**Comment by VlaDexa** [comment]
Because there was no package version change (pkgrel bump), yay thinks that the locally cached PKGBUILD with old dependency on python-pywal is ok to use and doesn't need updating and keeps locally the old dependency chain. It even won't easily update to the new PKGBUILD, because during install it will say "PKGBUILD up to date"

```sh
> yay -S pywal-spicetify
AUR Explicit (1): pywal-spicetify-0.1.1-1
:: PKGBUILD up to date, skipping download: pywal-spicetify
```

When the installed package says that it still depends on python-pywal
```sh
> LC_ALL=C.UTF-8 yay -Qi pywal-spicetify
Name            : pywal-spicetify
Version         : 0.1.1-1
Description     : Apply wal colors to spicetify
Architecture    : x86_64
URL             : https://github.com/jhideki/pywal-spicetify
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-pywal  spicetify-cli
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 909.27 KiB
Packager        : Unknown Packager
Build Date      : Tue Jul 30 06:59:57 2024
Install Date    : Tue Jul 30 07:00:01 2024
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by jhideki** [comment]
Ah, I see. So if I update the version in the pkgrel number by 1 it swill force the Yay to pull in the updates?

**Comment by VlaDexa** [comment]
Yeah, now it works 
```
3  aur/pywal-spicetify                            0.1.1-1              -> 0.1.1-2
```

```sh
> LC_ALL=C.UTF-8 yay -Qi pywal-spicetify
Name            : pywal-spicetify
Version         : 0.1.1-2
Description     : Apply wal colors to spicetify
Architecture    : x86_64
URL             : https://github.com/jhideki/pywal-spicetify
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : pywal-16-colors  spicetify-cli
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 909.27 KiB
Packager        : Unknown Packager
Build Date      : Wed Jul 31 21:01:09 2024
Install Date    : Wed Jul 31 21:01:16 2024
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

Don't forget to change pkgrel back to 1 on your next code release.  Thanks again for this tool!

**Comment by jhideki** [comment]
Glad it works! Thanks for all the help btw. I'm fairly new to Arch so youve been a huge help
